### ISSUE TITLE
Full tracebacks written instead of single log

### ISSUE THREAD

**Issue by RoelantStegmann** [jruere/multiprocessing-logging#59]
In python 3.9.0 with multiprocessing 0.3.3 we keep getting full tracebacks printed instead of single logs

```
        install_mp_handler()
        _calculate_several = partial(self._calculate_several_unpack)
        with mp.Pool(processes=len(inputs), initializer=install_mp_handler) as pool:
            results = pool.map(_calculate_several, inputs)
        pool.join()
```

It seems to print the full traceback for each individual message it tries to log from one of the installed packages:

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/multiprocessing_logging.py", line 115, in emit
    self._send(s)
  File "/usr/local/lib/python3.9/site-packages/multiprocessing_logging.py", line 96, in _send
    self.queue.put_nowait(s)
  File "/usr/local/lib/python3.9/multiprocessing/queues.py", line 138, in put_nowait
    return self.put(obj, False)
  File "/usr/local/lib/python3.9/multiprocessing/queues.py", line 88, in put
    raise ValueError(f"Queue {self!r} is closed")
ValueError: Queue <multiprocessing.queues.Queue object at 0x7f29c9bcf130> is closed
Call stack:
  File "/opt/code/entrypoints/entrypoint_calculation.py", line 118, in <module>
    ....
  File "/usr/local/lib/python3.9/site-packages/train/cell/dot_product_rnn_cell.py", line 79, in __init__
    logger.info("Created Cell")
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 952, in handle
    self.emit(record)
  File "/usr/local/lib/python3.9/site-packages/multiprocessing_logging.py", line 119, in emit
    self.handleError(record)
Message: 'Created Cell'
Arguments: ()
```

**Comment by jruere** [comment]
@RoelantStegmann could you provide a small scrip that reproduces this problem?

**Comment by jruere** [comment]
@RoelantStegmann a new release has improvements for 3.9+. I don't think they are related to this issue but let me know if it helps.

**Comment by jruere** [comment]
Also, please don't pass that initializer (`initializer=install_mp_handler`). That's a mistake.

**Comment by jruere** [comment]
I think the mistake explains the behavior. Reopen otherwise.
