### ISSUE TITLE
OSError: handle is closed

### ISSUE THREAD

**Issue by miohtama** [jruere/multiprocessing-logging#60]
Looks like `multiprocessing-logging` has some issues in the case of a child process crashing. In my case it is the child process:

```
 OSError: handle is closed
   File "/usr/local/lib/python3.10/site-packages/multiprocessing_logging.py", line 81, in _receive
     record = self.queue.get(timeout=0.2)
 Traceback (most recent call last):
   File "/usr/local/lib/python3.10/site-packages/multiprocessing_logging.py", line 81, in _receive
     record = self.queue.get(timeout=0.2)
 OSError: handle is closed
   File "/usr/local/lib/python3.10/multiprocessing/queues.py", line 113, in get
     if not self._poll(timeout):
 Traceback (most recent call last):
   File "/usr/local/lib/python3.10/multiprocessing/connection.py", line 136, in _check_closed
     raise OSError("handle is closed")
   File "/usr/local/lib/python3.10/site-packages/multiprocessing_logging.py", line 81, in _receive
     record = self.queue.get(timeout=0.2)
 Traceback (most recent call last):
```

Not sure yet what is the right solution here,  but ironically this error message is polluting logs.

**Comment by miohtama** [comment]
Looks like could be a duplicate of https://github.com/jruere/multiprocessing-logging/issues/56
